/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Controlador;

/**
 *
 * @author willianmurayama
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        AssignmentProblem = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        FractionalKnapsackProblem = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        CodificacaoHuffman = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        KnapsackProblem = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        LongestCommonSubsequence = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Branch and bound");

        javax.swing.GroupLayout AssignmentProblemLayout = new javax.swing.GroupLayout(AssignmentProblem);
        AssignmentProblem.setLayout(AssignmentProblemLayout);
        AssignmentProblemLayout.setHorizontalGroup(
            AssignmentProblemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AssignmentProblemLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(756, Short.MAX_VALUE))
        );
        AssignmentProblemLayout.setVerticalGroup(
            AssignmentProblemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AssignmentProblemLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(485, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Assignment problem", AssignmentProblem);

        jLabel3.setText("Algoritmo guloso");

        javax.swing.GroupLayout FractionalKnapsackProblemLayout = new javax.swing.GroupLayout(FractionalKnapsackProblem);
        FractionalKnapsackProblem.setLayout(FractionalKnapsackProblemLayout);
        FractionalKnapsackProblemLayout.setHorizontalGroup(
            FractionalKnapsackProblemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FractionalKnapsackProblemLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(761, Short.MAX_VALUE))
        );
        FractionalKnapsackProblemLayout.setVerticalGroup(
            FractionalKnapsackProblemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FractionalKnapsackProblemLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(485, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Fractional Knapsack problem", FractionalKnapsackProblem);

        jLabel2.setText("Algoritmo guloso");

        javax.swing.GroupLayout CodificacaoHuffmanLayout = new javax.swing.GroupLayout(CodificacaoHuffman);
        CodificacaoHuffman.setLayout(CodificacaoHuffmanLayout);
        CodificacaoHuffmanLayout.setHorizontalGroup(
            CodificacaoHuffmanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CodificacaoHuffmanLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(761, Short.MAX_VALUE))
        );
        CodificacaoHuffmanLayout.setVerticalGroup(
            CodificacaoHuffmanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CodificacaoHuffmanLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(485, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Codificação de Huffman", CodificacaoHuffman);

        jLabel4.setText("Programação Dinâmica");

        javax.swing.GroupLayout KnapsackProblemLayout = new javax.swing.GroupLayout(KnapsackProblem);
        KnapsackProblem.setLayout(KnapsackProblemLayout);
        KnapsackProblemLayout.setHorizontalGroup(
            KnapsackProblemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(KnapsackProblemLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addContainerGap(730, Short.MAX_VALUE))
        );
        KnapsackProblemLayout.setVerticalGroup(
            KnapsackProblemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(KnapsackProblemLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addContainerGap(485, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Knapsack problem", KnapsackProblem);

        jLabel5.setText("Programação Dinâmica");

        javax.swing.GroupLayout LongestCommonSubsequenceLayout = new javax.swing.GroupLayout(LongestCommonSubsequence);
        LongestCommonSubsequence.setLayout(LongestCommonSubsequenceLayout);
        LongestCommonSubsequenceLayout.setHorizontalGroup(
            LongestCommonSubsequenceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LongestCommonSubsequenceLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addContainerGap(730, Short.MAX_VALUE))
        );
        LongestCommonSubsequenceLayout.setVerticalGroup(
            LongestCommonSubsequenceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LongestCommonSubsequenceLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addContainerGap(485, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Longest Common Subsequence", LongestCommonSubsequence);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 873, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AssignmentProblem;
    private javax.swing.JPanel CodificacaoHuffman;
    private javax.swing.JPanel FractionalKnapsackProblem;
    private javax.swing.JPanel KnapsackProblem;
    private javax.swing.JPanel LongestCommonSubsequence;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
